### ISSUE TITLE
Support for Dawn Pro

### ISSUE THREAD

**Issue by adokitkat** [Tommy-Geenexus/usb-dongle-control#3]
Hi, I would like to ask if supporting MOONDROP Dawn Pro would be possible?

I have the device so I can help if you needed some info (Wireshark data etc.). Thanks!

**Comment by Tommy-Geenexus** [comment]
Sure, i would need some more details.

Namely: 

- USB model name
- USB product id
- Preferably an overview of which parameters can be controlled via moondrop link (assume it offers the same controls as the og dawn)

You can retrieve the model name/product id on linux with `lsusb`.
E.g. for the dawn 4.4mm the output would be
```
lsusb
...
Bus 007 Device 005: ID 2fc6:f067 Comtrue Inc. Nano audio 1
...
```

**Comment by Epikest** [comment]
```
$ lsusb
...
Bus 001 Device 002: ID 2fc6:f06a Comtrue Inc. MOONDROP Dawn Pro
...
```
![Screenshot_20231125-104523](https://github.com/Tommy-Geenexus/usb-dongle-control/assets/45499416/8f23eb5f-d39d-4bc0-9c88-38c4d62fc205)
![Screenshot_20231125-104526](https://github.com/Tommy-Geenexus/usb-dongle-control/assets/45499416/f24cc173-eaa5-4e17-9e52-68a4cbc9752f)
![Screenshot_20231125-104529](https://github.com/Tommy-Geenexus/usb-dongle-control/assets/45499416/e7c412b9-01bf-4918-98e1-94f0d5e65352)
![Screenshot_20231125-104531](https://github.com/Tommy-Geenexus/usb-dongle-control/assets/45499416/1518b71b-e98d-45d6-840e-aa35d67da90b)
